# Generated by Django 3.2.4 on 2021-06-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Delete')),
                ('activity_category_name', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Activity Category',
                'verbose_name_plural': 'Activities Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Delete')),
                ('project_category_name', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Projects Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Delete')),
                ('project_name', models.CharField(max_length=30)),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Recurrent Project')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_time', models.DurationField(default=None)),
                ('break_time', models.DurationField(default=None)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Project Category')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Delete')),
                ('project_name', models.CharField(max_length=30)),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Recurrent Project')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('work_time', models.DurationField(default=None)),
                ('break_time', models.DurationField(default=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectcategory', verbose_name='Project Category')),
            ],
            options={
                'verbose_name': 'historical Project',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalActivity',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Modified date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Delete')),
                ('activity_name', models.CharField(max_length=30)),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Recurrent Project')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.activitycategory', verbose_name='Project Category')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Activity',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Delete')),
                ('activity_name', models.CharField(max_length=30)),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Recurrent Project')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.activitycategory', verbose_name='Project Category')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
