# Generated by Django 3.2.4 on 2021-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sub', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.URLField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
